# Generated by Django 5.0.3 on 2024-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
        migrations.AlterField(
            model_name='employee',
            name='med_info',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
