# Generated by Django 5.0.3 on 2024-03-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_question_question_question_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='manager_id',
            new_name='boss',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='form_id',
            new_name='form',
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
